# Generated by Django 4.2.19 on 2025-03-30 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_alter_task_report_statusupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='description',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
