# Generated by Django 4.2.19 on 2025-03-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_alter_complaint_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusupdate',
            options={},
        ),
        migrations.RemoveField(
            model_name='statusupdate',
            name='notes',
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demoapp.complaint'),
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='from_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demoapp.report'),
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='to_status',
            field=models.CharField(max_length=20),
        ),
    ]
